### ISSUE TITLE
implement Imgix in drupal 7

### ISSUE THREAD

**Issue by thedappernisarg** [wieni/imgix#15]
Hi 

I am trying to to implement imgix in drupal. I have read few articles but does not work. Can you guide me to implement imgix. 
@spoit you are one of the contributes for imgix Drupal module.
 Thank You

**Comment by spoit** [comment]
Hi!,

Sure, can you please give a more detailed description where you're stuck? Are you using the github version of the module or the drupal.org version? (which are two quite different beasts).

Kind regards,

Bart

**Comment by thedappernisarg** [comment]
@spoit Thank You! 

I am trying to implement the available third party module: 
[https://www.drupal.org/project/imgix](https://www.drupal.org/project/imgix). I would like to implement the module in Drupal 7 and using FTP and seems been tricky for me. 

My questions are: 
1) Is this modules go in `sites/all/modules` ? And what If I had an `sites/all/modules/contrib' module available. 
2) Is` composer manager ` require for this modules. I already had vendor directory includes drush and composer  under themes directory  `themes/vendor`. I am not finding enough information on it. 
I have asked Imgix support. But, they are not providing support in drupal and I need to contact to contributors for imgix third party integration.
3) What if I have to use github version of Imgix?

If you can guide me, that would be really appreciated. Let me know, if you have need any other details. 

Thanks again.

**Comment by spoit** [comment]
Hi.

1. ```sites/all/modules``` or ```sites/all/modules/contrib``` are both fine. Every folder within ```sites/all/modules``` is fine.

2. https://www.drupal.org/project/composer_manager is indeed required in order to load the Imgix Classes for the module to work. You can see we use the class in https://cgit.drupalcode.org/imgix/tree/imgix.inc to create Imgix signed urls. You can read https://www.drupal.org/node/2405789 to see how to install composer manager correctly for Drupal 7.

3. The github version is Drupal 8 only.

**Comment by thedappernisarg** [comment]
@spoit Great. let me workaround on this. 
Thank You!
